### ISSUE TITLE
Will support tensorflow framework？

### ISSUE THREAD

**Issue by zuston** [vycezhong/rayps#4]
Thanks for your great work.
I am also very interested in Ray, and I am also investigating how to implement a parameter server to support online learning under the TensorFlow framework.

So in this project, will support tf?

**Comment by jasperzhong** [comment]
Hi. It is a toy example of parameter servers. It is inefficient, and there is still a lot of room for optimization. BTW, why would you consider using Ray?

**Comment by zuston** [comment]
Does Ray provide PS module ? It looks like no such solution.

**Comment by jasperzhong** [comment]
Have you read this? https://docs.ray.io/en/master/auto_examples/plot_parameter_server.html

**Comment by zuston** [comment]
Thanks. Let me take a look.

**Comment by zuston** [comment]
Ray is powerful. I have implemented Parameter Server for TF by Ray. Thanks for your advice above. @vycezhong
